# Generated by Django 3.0.6 on 2020-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('href', models.TextField(default='')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='api.Tag')),
            ],
        ),
    ]
