# Generated by Django 3.0.6 on 2020-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='href',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
